// ===== Supabase設定 =====
// Supabase管理画面 > Project Settings > API から取得して設定する
const SUPABASE_URL = 'https://helhoqowoizeseefvhzu.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbGhvcW93b2l6ZXNlZWZ2aHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1NjI3NzQsImV4cCI6MjA5NzEzODc3NH0.-8Jw7FiPegkbojyj2YtXPdEIY7MJJWl09_AM_EMB-gY';

// ===== サイト設定 =====
// ここを自分の情報に書き換える
const SITE_CONFIG = {
  siteName: 'Atelier de Ruka',
  creatorName: 'るか',
  tagline: '手に取った瞬間、ときめきが止まることのない宝箱を',
  subTagline: '推しを一番美しく輝かせる、高密度なホイップデコケースを制作しています✨',
  aboutText: '🌹 ホイップデコ / レジン / トレカケース\n💎 宝石箱のような贅沢なデコレーション\n🎁 丁寧な梱包と心を込めた手仕事\n🏢 フルタイム勤務の傍ら、一点ずつ大切に制作中',
  orderEmail: 'ichigo.oremilk@gmail.com',
  sns: {
    youtube:   'https://www.youtube.com/@%E3%82%8B%E3%81%8B%E3%81%AE%E6%89%8B%E8%8A%B8%E9%83%A8%E5%B1%8B',
    instagram: 'https://www.instagram.com/rkaaaaaaan_/',
    mercari:   'https://jp.mercari.com/user/profile/208138567',
    yahoo:     'https://paypayfleamarket.yahoo.co.jp/user/p54911909',
  },
};

/*
 * ===== Supabase テーブルのセットアップ手順 =====
 *
 * 1. https://supabase.com でプロジェクトを作成
 * 2. 管理画面の「SQL Editor」で以下のSQLを実行：
 *
 * create table works (
 *   id bigint generated by default as identity primary key,
 *   title text not null,
 *   description text,
 *   category text default 'その他',
 *   image_url text,
 *   price integer,
 *   status text default 'available',
 *   created_at timestamptz default now()
 * );
 *
 * alter table works enable row level security;
 *
 * create policy "公開読み取り" on works for select using (true);
 * create policy "公開追加"     on works for insert with check (true);
 * create policy "公開更新"     on works for update using (true);
 * create policy "公開削除"     on works for delete using (true);
 *
 * 3. 管理画面の「Project Settings > API」から
 *    Project URL と anon public key をコピーして上に設定する
 */
